# Generated by Django 5.0.1 on 2024-01-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_description_profile_hasvoted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numberOfVotes',
            field=models.IntegerField(default=100000),
        ),
    ]
