# Generated by Django 5.0.1 on 2024-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_numberofvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numberOfVotes',
            field=models.IntegerField(default=0),
        ),
    ]
