# Generated by Django 5.0.1 on 2024-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasCandidated',
            field=models.BooleanField(default=False),
        ),
    ]
