# Generated by Django 5.0.1 on 2024-01-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_hascandidated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hasCandidated',
            new_name='hasApplied',
        ),
    ]
