# Generated by Django 5.0.1 on 2024-01-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_displayusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displayUsers',
        ),
    ]
