# Generated by Django 5.0.1 on 2024-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_displayusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='votedFor',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
