# Generated by Django 5.0.1 on 2024-02-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_profile_votedfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkFacebook',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkInstagram',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkLinkedin',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
