# Generated by Django 5.0.1 on 2024-02-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='event_end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='event_start_date',
        ),
    ]
