# Generated by Django 5.0.1 on 2024-02-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
