# Generated by Django 5.0.1 on 2024-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winner',
            field=models.TextField(blank=True, default=' ', max_length=500),
        ),
    ]
